#!/bin/bash

git clone https://github.com/riveSunder/carle.git

cd carle
pip install .

cd ../

python -c "from carle.carle.env import CARLE; env = CARLE(); print('Looks OK')"


# enable jupyter_server_proxy
jupyter serverextension enable --sys-prefix jupyter_server_proxy
# install the bokeh server extension so that bokeh launches at startup
mv bokehserverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/
# enable bokeh extension
jupyter serverextension enable --sys-prefix bokehserverextension
